### ISSUE TITLE
Newbie question, how to call refresh method?

### ISSUE THREAD

**Issue by drewpotter** [vanderlee/coverflow#13]
Hello,

I have a really newbie question. I am using the coverflow in my App and I am appending covers to the end and I want to call the refresh method but I don't seem to be able to do it.

I am calling:

$('#preview-coverflow').coverflow.refresh();

Please can you help me to write the correct command?

Thanks

**Comment by vanderlee** [comment]
It's the same as for the default jQuery-UI plug-ins; you call coverflow with the method name as first argument: `$('#preview-coverflow').coverflow('refresh');`
