### ISSUE TITLE
How to modify an individual option say index option after calling overflow?

### ISSUE THREAD

**Issue by kratos6753** [vanderlee/coverflow#15]
$(function() {
		if ($.fn.reflect) {
			$('.coverflow .cover').reflect();	// only possible in very specific situations
		}

		$('.coverflow').coverflow({
			index:			6,
			density:		2,
			innerOffset:	50,
			innerScale:		.7,
			animateStep:	function(event, cover, offset, isVisible, isMiddle, sin, cos) {
				if (isVisible) {
					if (isMiddle) {
						$(cover).css({
							'filter':			'none',
							'-webkit-filter':	'none'
						});
					} else {
						var brightness	= 1 + Math.abs(sin),
							contrast	= 1 - Math.abs(sin),
							filter		= 'contrast('+contrast+') brightness('+brightness+')';
						$(cover).css({
							'filter':			filter,
							'-webkit-filter':	filter
						});
					}
				}
			}
		});
		$('.coverflow').coverflow({index:1});
	});

I tried above code but still the selected index is 6.Please help me how to modify the individual options are declaration of coverflow call.

**Comment by sburkett** [comment]
If I understand what you are trying to do, you can set the index manually like this:

`$('.coverflow').coverflow('index', value);
