### ISSUE TITLE
Display a text in the current selected cover?

### ISSUE THREAD

**Issue by angelochen960** [vanderlee/coverflow#16]
Hi,

Is there a way to display a text in the selected cover? following the demo, a text can be displayed below the cover, possible to display it on top of the cover photo? Thanks.

```
  select:		function(event, cover) {
              var img = jQuery(cover).children().andSelf().filter('img').last();
              jQuery('#photos-name').text(img.data('name') || 'unknown');
            }
```

**Comment by vanderlee** [comment]
Easiest would probably be to handle the location of the div using CSS. Use a z-index to push it in fron of the covers.
