### ISSUE TITLE
how to display the dots kind of pagination below the coverflow

### ISSUE THREAD

**Issue by ravikiranr26** [vanderlee/coverflow#17]
Below the coverflow need to display the dots/ to select by click like pagination. How can i set it up ?

**Comment by ravikiranr26** [comment]
![test](https://cloud.githubusercontent.com/assets/1841796/6326520/9f85a43a-bb78-11e4-819c-e45cd41f2e6a.png)


I need to have the coverflow with text and navigation with button too. can we do achieve it ?

**Comment by vanderlee** [comment]
Coverflow does not have it's own dots or controls, but it has plenty of events and methods that let you add your own controls and dots. You might want to check the buttons on the topmost example on the page http://vanderlee.github.io/coverflow/test.html (included in the download).

For the prev/next buttons you could use the 'index' method to first get, then set (adding or subtracting 1) the current index.

For the dots you could use the 'change' event. It's third parameter is the current index, which you could use in a jQuery ':eq' selector to change your dot colors. The second example on the page mentioned above shows how to use the change event, although not for dots.

**Comment by vanderlee** [comment]
Out of boredom, I made a small jsfiddle which demonstrates how to do the pagination and dots:
http://jsfiddle.net/7hfb4p1a/3/

**Comment by ravikiranr26** [comment]
Hi Martijn van der Lee,

Awesome thanks for the wonderfull help.

On Tue, Feb 24, 2015 at 3:15 AM, Martijn van der Lee <
notifications@github.com> wrote:

> Out of boredom, I made a small jsfiddle which demonstrates how to do the
> pagination and dots:
> http://jsfiddle.net/7hfb4p1a/3/
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/vanderlee/coverflow/issues/17#issuecomment-75642501>.
>



-- 
Thanks & Regards
Ravi Kiran .R
