### ISSUE TITLE
animateComplete fires too many times

### ISSUE THREAD

**Issue by santicalvo** [vanderlee/coverflow#19]
I found out that animateComplete fires a lot of times, not just once, so there's no reliable way to detect the ending of an animation.

**Comment by stuthemoo** [comment]
I also have the same problem, I'd really like to have a callback that fires when the animation is completed.

**Comment by stuthemoo** [comment]
Because I'm using controls to manually go back and forth I've managed to use setTimeout as a callback function which works well. Here's my code:

var current_cover = $('.coverflow').coverflow('index');
`$('.coverflow').coverflow('index', current_cover + 1);

setTimeout(function () {
	alert('Animation complete!');
}, 500);`

**Comment by vanderlee** [comment]
The animateComplete event is meant for postprocessing each individual cover at the end of every animation, hence it fires once for each cover for every change. For example; the alphabet examples fires it exactly 26 times after each keypress.

You should probably use the select and/or change events. If these are not sufficient, please let me know.
