### ISSUE TITLE
Option to disable mousewheel and keyboard?

### ISSUE THREAD

**Issue by macsupport** [vanderlee/coverflow#21]
A suggestion to add the option to enable/disable mousewheel ( especially) and keyboard navigation.

**Comment by vanderlee** [comment]
Disabling features is usually pretty easy, so I'll look into it later today.
But I am curious as to the use case for a coverflow with neither mousweheel nor keyboard control?

**Comment by macsupport** [comment]
I have implemented a previous/next button instead:

````
$(function() {
var indexC = $('#coverflow' ).coverflow( 'index');
$( ".preButton" ).on("click",function() {	
		$('#coverflow' ).coverflow( 'index' ,indexC - 1 );
            });			
		});

	$( ".nextButton).click(function() {
			$('#coverflow' ).coverflow( 'index',indexC + 1 );
            });
		});
});
````

 but more importantly is the mouse wheel behavior with a trackpad. Impossibly fast with lack of fine control. I also have a popup info button within each cover with scrollable text and using the mouse wheel to scroll text moves the coverflow instead. The keyboard is not really an issue with my use.

**Comment by vanderlee** [comment]
I can't reproduce the issues with trackpad. Tried on an Ubuntu 14.04 laptop, so it might be different for a different OS (or even a different trackpad type).

**Comment by vanderlee** [comment]
Added support for enableKeyboard, enableClick and enableWheel (all boolean, all true by default). The events actually keep running (may be improved in the future), so it's easy to enable/disable at will. See demo.

**Comment by kermit524** [comment]
Hi,
Thanks for your plugin! I came across this thread trying to disable the mousewheel on coverflow display. Unfortunately I am no luck. The coverflow element is initiated like so:
$('#coverflow').coverflow({'enableWheel':false});
The wheel is still enabled.
What do I do wrong?
Many thanks in advance,
Michal
