### ISSUE TITLE
Suggestion for new event

### ISSUE THREAD

**Issue by sburkett** [vanderlee/coverflow#23]
When doing something like this:

$(".coverflow").coverflow('index', 5);

It would be incredibly awesome to have an event that fires once the newly selected index has completed animating and is visible/in-scope.  Right now, as far as I can tell, there isn't a way to do that without resorting to trying to use animateComplete which fires on each frame, and trying to calculate when you are at the new one.  Hope that makes sense!

Cheers.

**Comment by vanderlee** [comment]
Won't the `stop` event do?

**Comment by sburkett** [comment]
Sounds like it might!  I didn't see it in the docs, so it might be helpful to give that a quick edit.  I'll give it a go, thanks!

**Comment by sburkett** [comment]
In looking at the coverflow code, I don't see a stop() method, so I think you are talking about the jQuery stop() method instead?  I've never used that, but I'll start reading up on it!

**Comment by sburkett** [comment]
Well, one way that I have it working now is by calling the jQuery finish() method.  That at least puts the coverflow on the right item.  But the animation is skipped, obviously.  :(

**Comment by vanderlee** [comment]
I think I might have been mixing up some of my plug-ins. Sorry about that :)
The `animation` events are meant for the animations, they may trigger multiple times if needs be.
I'll see what I can do to add an event, which shouldn't be hard.

**Comment by sburkett** [comment]
That's awesome, thanks! I look forward to it.  BTW, kudos for the amazing support of this plugin.  This is by far one of the better plugins I've seen/used, and it is always refreshing to see authors not letting their creations die on the vine, as so many do here.  Keep up the good work!

**Comment by vanderlee** [comment]
Finally got around to this.
Seems the `select` and `change` already cover this. The `change` event is triggered as soon as the animation has moved to the "destination" index but before all animation is done, the `select` event is triggered after all animation is done. That should cover all situations.
It should be noted that the `select` event is also triggered on initialisation.

Please reopen if this does not sufficiently answer the issue.
