### ISSUE TITLE
Coverflow only shows one cover div ?

### ISSUE THREAD

**Issue by dan2k3k4** [vanderlee/coverflow#24]
I am using ionic, and my init code is basically :

                            $('.collection-repeat-container').coverflow({
                                easing: 'easeOutElastic',
                                duration: 'slow',
                                width: 300,
                                height: 600,
                                visible: 'density',
                                selectedCss: {
                                    opacity: 1
                                },
                                outerCss: {
                                    opacity: .1
                                },
                                confirm: function() {
                                    console.log('confirm?');
                                },
                                change: function(event, cover) {
                                    var img = $(cover).children().andSelf().filter('img').last();
                                    $('#coverflow-title').text(img.data('name') || 'unknown');
                                }
                            });

but I only see one cover, if I scroll - it sort of "flips" left and right for others but you can only ever see one. How can I get it to show all covers in the background?

**Comment by vanderlee** [comment]
Probably the size of the area. Coverflow displays as many covers as fit in the screenspace, but no more.
Try changing the are or the `width` option.
Otherwise, please post a jsfiddle or similar that demonstrates the issue.

**Comment by dan2k3k4** [comment]
It seems to be a problem with collection-repeat directive in ionic - it would add transform/height/width attributes to position each item on the screen within the elements style attribute... I've switched to ng-repeat but have other issues with making tabs stay on current page -_-

Anyway, I'll close as irrelevant to coverflow
