### ISSUE TITLE
Focus onload

### ISSUE THREAD

**Issue by jamesdwilson** [vanderlee/coverflow#28]
Is it possible to focus the coverflow component on page load? Arrow keys do not seem to work unless I click on the component first.

**Comment by robred** [comment]
I have noticed this behavior as well

**Comment by vanderlee** [comment]
Currently, coverflow has no real focus. I guess something could be done using `tabindex` or similar to gain keyboard focus.

**Comment by vanderlee** [comment]
Finally got around to this issue. Added support for focus (no need to do anything), autofocus (if attribute set on element) and some extra choices to the `enableKeyboard` option to specify how the keyboard is used. Currently default is `both` but I may change this to `hover` if it causes backwards compatibility issues.

**Comment by jamesdwilson** [comment]
Thanks so much!
