### ISSUE TITLE
Only one cover is show

### ISSUE THREAD

**Issue by neojanus** [vanderlee/coverflow#29]
Hi,

First very great plugin, 

my issue is that the coverflow script only show one cover (but in the dom i see all my cover) only when i change the size of the screen manually that all the cover load.

somebody got the same issue ?

Thanks

**Comment by vanderlee** [comment]
Many people have been using this plug-in without this problem, so likely it's caused by your specific use case.
Do you have an example in jsfiddle or similar?

**Comment by neojanus** [comment]
Hi,

Thanks for your reply, i solved the problem yes it was a specific use case. 

Best regards
