### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Mr-Alexander** [vanderlee/coverflow#30]
Hi,

Great plugin.

It would be great if you can please explain the role of the dependencies and document it a little. 

For example, what jQuery UI features are needed if I would like to download a version from the website?

What are these:

- markdown.converter.min.js
- jquery.interpolate.js

Thank you for your help.

Mr Alexander

**Comment by vanderlee** [comment]
I've added the single jQueryUI part that is needed; Widgets.

`Markdown.converter.min.js` is only required by the index.html to show the readme.md file and is not used by Coverflow itself so will not be documented.

All extra JS files are optional, but work with Coverflow when used. I'll see if I can document them.

`jquery.interpolate.js` in particular (another project of mine; https://github.com/vanderlee/interpolate) is required if you use custom `innerCss` and `outerCss`.

Use `touchSwipe` if you want to use touch to swipe on a touchscreen device. You can probably use other javascript libaries that support the `.swipe()` event.

`reflection.js` is just a nice gimmick to add reflections. Coverflow itself does not use it, but the demo's will. Coverflow DOES take some minor precautions to support it's use.

**Comment by vanderlee** [comment]
I've added documentation as requested.
